//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by Quanlytailieu.rc
//
#define DLG_LIST_UPDATE                 1000
#define DLG_OPTION_MAIN                 1002
#define DLG_COPY_DATA                   1003
#define DLG_ADD_DATA                    1004
#define IDI_ICON_SEARCH                 1006
#define IDR_MENU_ADDDATA                1007
#define IDI_ICON_ADD                    1008
#define IDI_ICON_COPY                   1009
#define IDI_ICON_DELETE                 1010
#define IDI_ICON_MOVE                   1011
#define IDI_ICON_OPENFOLDER             1013
#define IDI_ICON_SEND                   1015
#define DLG_CHECK_FILES                 1016
#define DLG_RIBBON_TIMKIEM              1018
#define IDR_MENU_RBSEARCH               1020
#define IDI_ICON_ARROW                  1021
#define DLG_INSERT_ROWS                 1022
#define IDI_ICON_UPDATE                 1024
#define IDI_ICON_GEAR                   1025
#define IDI_ICON_COMPARE                1027
#define IDI_ICON_TODOLIST               1028
#define DLG_CREATE_NEWTEMP              1032
#define IDR_MENU_CHECKFILES             1035
#define IDR_MENU_LISTUPDATE             1038
#define DLG_RENAME_FILES                1039
#define IDR_MENU_RENAME                 1042
#define DLG_CREATE_GROUPS               1043
#define IDI_ICON_TREE                   1045
#define DLG_CHANGE_HYPERLINK            1046
#define IDI_ICON_QUESTION               1048
#define IDI_ICON_SHORTCUT               1049
#define IDI_ICON_SUPPORT                1050
#define IDI_ICON_ADDLIST                1051
#define IDI_ICON_ADD_FILE               1052
#define DLG_STRUCTURE                   1053
#define IDI_ICON_RENAME                 1053
#define DLG_DIRSTRUCTURE                1054
#define IDI_ICON_CHART                  1056
#define IDI_ICON_OPENFILE               1057
#define IDI_ICON_TREE_STRUCT            1058
#define DLG_EDITPROPERTIES              1059
#define IDI_ICON_PROPERTIES             1061
#define IDI_ICON_COPYCLIP               1062
#define IDR_MENU_PROPERTIES             1063
#define IDI_ICON_BROOM                  1067
#define IDI_ICON_DOWN                   1068
#define IDI_ICON_SAVED                  1069
#define IDI_ICON_UP                     1070
#define DLG_SELECTION_CELLS             1071
#define IDI_ICON_NULL                   1073
#define IDR_MENU_REPLACE                1074
#define IDI_ICON_REPLACE                1075
#define DLG_AUTORENAME                  1078
#define FVIEW_RENAME_STT                1079
#define FVIEW_RENAME_ADD                1080
#define FVIEW_RENAME_DELETE             1081
#define IDR_MENU_AUTORENAME             1081
#define FVIEW_RENAME_REPLACE            1082
#define IDI_ICON_REVERSE                1082
#define FVIEW_RENAME_KHAC               1083
#define IDI_ICON_REDO                   1083
#define IDI_ICON_UNDO                   1084
#define IDI_ICON_CHECK                  1085
#define IDI_ICON_MAIN                   1086
#define IDI_ICON_OK                     1087
#define IDI_ICON_CANCEL                 1088
#define IDC_CURSOR_HAND                 1189
#define IDB_BITMAP_NOTIFIER             1190
#define UPD_LIST_VIEW                   2000
#define UPD_CHECK_ALL                   2001
#define UPD_BTN_OK                      2002
#define UPD_BTN_CANCEL                  2003
#define OPTM_TXT_BROWSE                 2004
#define OPTM_CBB_AUTOUPDATE             2005
#define OPTM_BTN_BROWSE                 2006
#define OPTM_CHECK_MSGUPDATE            2007
#define OPTM_CHECK_MSGERROR             2008
#define OPTM_CHECK_START_WINDOWS        2009
#define OPTM_CHECK_DEL_FILECSV          2010
#define OPTM_BTN_OK                     2011
#define OPTM_BTN_CANCEL                 2012
#define OPTM_CHECK_THREAD               2013
#define OPTM_CHECK_DEL_FILECSV2         2014
#define OPTM_BTN_REGISTER_COM           2015
#define COPYDT_LIST_VIEW                2015
#define COPYDT_BTN_OK                   2016
#define COPYDT_BTN_CANCEL               2017
#define COPYDT_CHECK_ALL                2018
#define ADDDATA_TXT_BROWSE              2019
#define ADDDATA_TXT_TYPEFILE            2020
#define ADDDATA_BTN_BROWSE              2021
#define ADDDATA_CHECK_FOLDERSUB         2022
#define ADDDATA_CHECK_ALL               2023
#define ADDDATA_TXT_SEARCH              2024
#define ADDDATA_LIST_VIEW               2025
#define ADDDATA_BTN_SEARCH              2026
#define ADDDATA_BTN_OK                  2027
#define ADDDATA_BTN_CANCEL              2028
#define ADDDATA_LBL_SEARCH              2029
#define ADDDATA_LBL_BROWSE              2030
#define ADDDATA_LBL_TYPEFILE            2031
#define ADDDATA_TXT_TOTALFILES          2032
#define ADDDATA_LBL_TOTALFILES          2033
#define ADDDATA_RADIO_DIR               2034
#define ADDDATA_RADIO_SUBDIR            2035
#define ADDDATA_CHECK_COPY              2036
#define ADDDATA_RADIO_DEFAULT           2037
#define ADDDATA_RADIO_SELECTION         2038
#define ADDDATA_CBB_PATH                2039
#define ADDDATA_LINEVER                 2040
#define ADDDATA_SPLB_OK                 2041
#define ADDDATA_LBL_EXPS                2042
#define CHKFS_TXT_BROWSE                2043
#define CHKFS_BTN_BROWSE                2044
#define CHKFS_LIST_VIEW                 2045
#define CHKFS_BTN_OK                    2046
#define CHKFS_BTN_CANCEL                2047
#define CHKFS_LBL_BROWSE                2048
#define ADDDATA_TXT_PATHMOVE            2049
#define ADDDATA_BTN_PATHMOVE            2050
#define RBTK_CHECK_WB                   2051
#define RBTK_TXT_SEARCH                 2052
#define RBTK_BTN_SEARCH                 2053
#define RBTK_LIST_VIEW                  2054
#define RBTK_CHECK_COL                  2055
#define RBTK_BTN_CANCEL                 2056
#define RBTK_GRP_KQ                     2057
#define RBTK_BTN_GOTOCELL               2058
#define ISTROW_TXT_NUM                  2059
#define ISTROW_BTN_OK                   2060
#define ISTROW_BTN_CANCEL               2061
#define ISTROW_SPIN_NUM                 2062
#define CRENW_TXT_NAME                  2064
#define CRENW_BTN_OK                    2065
#define CHKFS_CHECK_ALL                 2066
#define CRENW_BTN_CANCEL                2066
#define CHKFS_CHECK_NEWS                2067
#define CHKFS_TXT_TOTALFILES            2068
#define CHKFS_LBL_TOTALFILES            2069
#define CHKFS_CBB_PATH                  2070
#define CHKFS_CHECK_LINK                2071
#define CHKFS_LBL_TOTALCHECK            2072
#define UPD_CHECK_SKIP                  2073
#define UPD_LIST_CATE                   2074
#define UPD_LBL_TOTAL                   2075
#define ADDDATA_LBL_TOTALCHECK          2076
#define RNMF_TXT_SEARCH                 2077
#define RNMF_LIST_VIEW                  2078
#define RNMF_BTN_OK                     2079
#define RNMF_BTN_CANCEL                 2080
#define RNMF_LBL_SEARCH                 2081
#define RNMF_BTN_SEARCH                 2082
#define RNMF_TXT_TYPEFILE               2083
#define RNMF_CHECK_ALL                  2084
#define RNMF_CHECK_NEWS                 2085
#define RNMF_TXT_TOTALFILES             2086
#define RNMF_LBL_TOTALFILES             2087
#define RNMF_LBL_TOTALCHECK             2088
#define RNMF_EDIT_VIEW                  2089
#define RNMF_LBL_HELP                   2090
#define ADDDATA_CHECK_TREEFOLDER        2091
#define CHKFS_RADIO_DIR                 2092
#define CHKFS_RADIO_SUBDIR              2093
#define CREGRS_BTN_OK                   2094
#define CREGRS_BTN_CANCEL               2095
#define CREGRS_GROUP                    2096
#define CREGRS_LIST_VIEW                2097
#define CHLINK_TXT_OLD                  2098
#define CHLINK_BTN_OLD                  2099
#define CHLINK_TXT_NEW                  2100
#define CHLINK_BTN_NEW                  2101
#define CHLINK_BTN_ADD                  2102
#define CHLINK_LIST_VIEW                2103
#define CHLINK_BTN_HELP                 2104
#define CHLINK_BTN_OK                   2105
#define CHLINK_BTN_CANCEL               2106
#define CHLINK_CHECK_SHEET              2107
#define CHLINK_LBL_OLD                  2108
#define ADDDATA_CHECK_GROUP             2109
#define ADDDATA_CBB_CELL                2110
#define ADDDATA_LBL_COPYMOVE            2111
#define STRC_TXT_PATH                   2111
#define STRC_TREE_VIEW                  2112
#define STRC_LIST_VEW                   2113
#define STRC_BTN_BROWSE                 2114
#define STRC_BTN_OK                     2115
#define STRC_BTN_CANCEL                 2116
#define STRC_LBL_PATH                   2117
#define STRC_LINE_TOP                   2118
#define STRC_LINE_BOTTOM                2119
#define STRC_BTN_TEMP                   2120
#define STRC_LBL_HDAN                   2121
#define STRC_LBL_OUTPUT                 2122
#define STRC_TXT_OUTPUT                 2123
#define STRC_BTN_OUTPUT                 2124
#define EDPR_TXT_SEARCH                 2124
#define EDPR_LIST_VIEW                  2125
#define EDPR_BTN_SEARCH                 2126
#define EDPR_BTN_CANCEL                 2127
#define EDPR_LBL_SEARCH                 2128
#define EDPR_BTN_UPDATE                 2129
#define EDPR_EDIT_VIEW                  2130
#define EDPR_GROUP_INFO                 2131
#define EDPR_TXT_FILENAME               2132
#define EDPR_STT_1                      2133
#define EDPR_STT_2                      2134
#define EDPR_TXT_TITLE                  2135
#define EDPR_STT_3                      2136
#define EDPR_TXT_SUBJECT                2137
#define EDPR_STT_4                      2138
#define EDPR_TXT_TAGS                   2139
#define EDPR_STT_5                      2140
#define EDPR_TXT_CATEGORIES             2141
#define EDPR_STT_6                      2142
#define EDPR_TXT_COMMENTS               2143
#define EDPR_STT_7                      2144
#define EDPR_TXT_AUTHORS                2145
#define EDPR_STT_8                      2146
#define EDPR_TXT_COMPANY                2147
#define EDPR_STT_9                      2148
#define EDPR_TXT_MANAGER                2149
#define EDPR_BTN_SAVED                  2150
#define EDPR_GROUP_LIST                 2151
#define EDPR_BTN_UP                     2152
#define EDPR_BTN_DOWN                   2153
#define EDPR_SPLITER_VER                2154
#define EDPR_BTN_CLEAR                  2155
#define EDPR_LINE_HOZ                   2156
#define SELCEL_RAD_SEL                  2158
#define SELCEL_RAD_GROUP                2159
#define SELCEL_RAD_ALL                  2160
#define SELCEL_BTN_OK                   2161
#define SELCEL_BTN_CANCEL               2162
#define SELCEL_GROUP                    2163
#define EDPR_LBL_PROGRESS               2164
#define STRC_TXT_NAME                   2165
#define CHLINK_LINE                     2166
#define CHLINK_LBL_NEW                  2167
#define CHLINK_BTN_DEL                  2168
#define CHLINK_BTN_UP                   2169
#define CHLINK_BTN_DOWN                 2170
#define CHLINK_LBL_HDAN                 2171
#define AUTORM_TXT_BROWSE               2172
#define TABSTT_TXT_NUM                  2175
#define TABSTT_SPIN_NUM                 2176
#define TABSTT_TXT_HAUTO                2177
#define TABSTT_CHECK_ZERO               2178
#define TABREP_CHK_CASE                 2178
#define TABADD_TXT_CHUOI                2179
#define TABREP_CHK_KODAU                2179
#define AUTORM_SPLIT_BROWSE             2180
#define TABSTT_CHECK_END                2181
#define TABSTT_CHECK_REPLACE            2182
#define TABADD_RAD_BEGIN                2182
#define TABADD_RAD_END                  2183
#define AUTORM_BTN_APDUNG               2184
#define TABADD_RAD_MID                  2184
#define AUTORM_BTN_OK                   2185
#define AUTORM_BTN_CANCEL               2186
#define TABREP_TXT_REP                  2186
#define TABDEL_RAD_ALL                  2187
#define TABREP_TXT_CHUOI                2187
#define TABDEL_RAD_BEGIN                2192
#define TABDEL_RAD_END                  2193
#define AUTORM_TABMAIN                  2194
#define TABDEL_RAD_LEFT                 2194
#define TABKHAC_RAD_UPPER               2195
#define AUTORM_LIST_VIEW                2196
#define TABKHAC_RAD_LOWER               2196
#define AUTORM_LBL_PATH                 2197
#define TABKHAC_RAD_UNSIGNED            2197
#define AUTORM_LINE_HORZ                2198
#define TABDEL_RAD_RIGHT                2198
#define TABKHAC_RAD_PROPER              2198
#define AUTORM_LINE_VER                 2199
#define TABKHAC_RAD_KODAU               2199
#define AUTORM_BTN_RESET                2200
#define AUTORM_BTN_UNDO                 2201
#define AUTORM_BTN_REDO                 2202
#define AUTORM_LBL_TOTAL                2203
#define AUTORM_CHECK_ALL                2204
#define AUTORM_LBL_HDAN                 2205
#define TABSTT_LBL_NUM                  2206
#define TABSTT_LBL_TIENTO               2207
#define TABSTT_LBL_VDTIENTO             2208
#define TABSTT_LBL_HAUTO                2209
#define TABSTT_LBL_VDHAUTO              2210
#define TABSTT_TXT_TIENTO               2211
#define TABSTT_LBL_VITRI                2212
#define TABADD_LBL_CHUOI                2212
#define TABADD_LBL_NUM                  2213
#define TABADD_TXT_NUM                  2214
#define TABADD_SPIN_NUM                 2215
#define TABADD_LBL_VIDUNUM              2216
#define TABDEL_TXT_CHUOI                2217
#define TABDEL_RAD_TRIM                 2218
#define TABDEL_RAD_SPACE                2219
#define TABDEL_RAD_CHUOI                2220
#define TABDEL_LBL_VTRI                 2221
#define TABDEL_LBL_CHUOI                2222
#define TABDEL_GROUP                    2223
#define TABDEL_LINE                     2224
#define TABREP_LBL_REP                  2225
#define TABREP_LBL_CHUOI                2226
#define AUTORM_EDIT_LIST                2227
#define MN_ADDATA_ADDFILES              32781
#define MN_ADDATA_COPYFILES             32782
#define MN_ADDATA_MOVEFILES             32783
#define MN_ADDATA_OPENFILE              32784
#define MN_ADDATA_OPENFOLDER            32785
#define MN_ADDATA_DELFILES              32786
#define MN_ADDATA_ADDFILES2             32787
#define MN_ADDATA_MOVEFILES2            32788
#define MN_ADDATA_COPYFILES2            32789
#define MN_RBSEARCH_GOTO                32792
#define MN_RBSEARCH_OPENFILE            32793
#define MN_RBSEARCH_OPENFOLDER          32795
#define MN_CHKFL_ADDFILES               32801
#define MN_CHKFL_OPENFILE               32802
#define MN_CHKFL_GOTOSHEET              32803
#define MN_CHKFL_DELFILES               32804
#define MN_CHKFL_OPENFOLDER             32805
#define MN_LSUP_CHECK                   32809
#define MN_LSUP_UNCHECK                 32810
#define MN_LSUP_CHECKALL                32811
#define MN_ADDATA_CHECK                 32816
#define MN_ADDATA_UNCHECK               32817
#define MN_ADDATA_CHECKALL              32818
#define MN_CHKFL_CHECK                  32823
#define MN_CHKFL_UNCHECK                32824
#define MN_CHKFL_CHECKALL               32825
#define MN_RENAME_RFILES                32834
#define MN_RENAME_OPENFILE              32835
#define MN_RENAME_OPENFOLDER            32836
#define MN_RENAME_DELETEFILES           32837
#define MN_RENAME_CHECK                 32838
#define MN_RENAME_UNCHECK               32839
#define MN_RENAME_CHECKALL              32840
#define MN_RENAME_COPY                  32842
#define MN_PROPERTIES_OPENFILE          32845
#define MN_PROPERTIES_OPENFOLDER        32846
#define MN_PROPERTIES_COPY              32849
#define MN_PROPERTIES_PASTE             32850
#define MN_REP_ADD                      32856
#define MN_REP_DEL                      32857
#define MN_REP_UP                       32858
#define MN_REP_DOWN                     32859
#define MN_AUTORN_FOLDER                32873
#define MN_AUTORN_FILES                 32874
#define MN_AUTORN_DELETE                32875
#define MN_AUTORN_APPLY                 32876
#define MN_AUTORN_OPENFILE              32877
#define MN_AUTORN_OPENFOLDER            32878
#define MN_AUTORN_UP                    32879
#define MN_AUTORN_DOWN                  32880
#define MN_AUTORN_REVERSE               32881
#define MN_AUTORN_SEL                   32882
#define MN_AUTORN_UNSEL                 32883
#define MN_AUTORN_SELALL                32885
#define MN_AUTORN_CHFILES               32888
#define MN_AUTORN_CHFOLDER              32889

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        1086
#define _APS_NEXT_COMMAND_VALUE         32890
#define _APS_NEXT_CONTROL_VALUE         2229
#define _APS_NEXT_SYMED_VALUE           1000
#endif
#endif
